#Raspberry Pi | Home Media Server

version: "3.9"

services:
  deluge:
    container_name: deluge
    image: ghcr.io/linuxserver/deluge
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /home/${USER}/seedbox/deluge:/config
      - /data:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp

  jackett:
    container_name: jackett
    image: ghcr.io/linuxserver/jackett
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - AUTO_UPDATE=true
      - RUN_OPTS=<run options here>
    volumes:
      - /home/${USER}/seedbox/jackett:/config
    ports:
      - 9117:9117

  radarr:
    container_name: radarr
    image: ghcr.io/linuxserver/radarr
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/${USER}/seedbox/radarr:/config
      - /data:/downloads
    ports:
      - 7878:7878

  sonarr:
    container_name: sonarr
    image: ghcr.io/linuxserver/sonarr
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/${USER}/seedbox/sonarr:/config
      - /data:/downloads
    ports:
      - 8989:8989

  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - JELLYFIN_PublishedServerUrl=http://example.com
    volumes:
      - /home/${USER}/seedbox/jellyfin:/config
      - /home/${USER}/seedbox/jellyfin/cache:/cache
      - /data:/downloads
    ports:
      - 8096:8096
