version: "3.9"

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: budry/jwilder-nginx-proxy-arm
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - confd:/etc/nginx/conf.d
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    container_name: letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion:stable
    restart: always
    volumes:
      - certs:/etc/nginx/certs:rw
      - confd:/etc/nginx/conf.d
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    expose:
      - 80
    volumes:
      - /home/pi/docker/web:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=lasudeste.duckdns.org
      - LETSENCRYPT_HOST=lasudeste.duckdns.org
      - LETSENCRYPT_EMAIL=achaval.lucas@gmail.com

volumes:
  certs:
  html:
  vhostd:
  confd:
