version: "3.9"

networks:
  front-tier:
  back-tier:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus:v2.25.2
    container_name: prometheus
    restart: always
    volumes:
      - /home/${USER}/monitoring/tools/prometheus/:/etc/prometheus/
      - /home/${USER}/monitoring/tools/prometheus:/data
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - 9090:9090
    external_links:
      # internet monitoring
      - ping
      - speedtest
    networks:
      - back-tier

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    volumes:
      - /home/${USER}/monitoring/tools/grafana:/data
      - /home/${USER}/monitoring/tools/grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
      - prometheus
    ports:
      - 3030:3000
    env_file:
      - /home/${USER}/monitoring/tools/grafana/config.monitoring
    networks:
      - back-tier
      - front-tier

  nodeexp:
    container_name: nodeexp
    image: prom/node-exporter
    restart: always
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    ports:
      - 9100:9100
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    networks:
      - back-tier

volumes:
  prometheus:
  grafana:
