{
 "title": "System Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"nodeexp\", instance=\"nodeexp:9100\"} - node_boot_time_seconds{job=\"nodeexp\", instance=\"nodeexp:9100\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{job=\"nodeexp\", instance=\"nodeexp:9100\", chip=\"thermal_thermal_zone0\", sensor=\"temp0\"}"
    }
   ]
  },
  {
   "title": "Available Disk",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{job=\"nodeexp\", instance=\"nodeexp:9100\", device=\"/dev/root\", fstype=\"ext4\", mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{job=\"nodeexp\", instance=\"nodeexp:9100\"}"
    }
   ]
  },
  {
   "title": "Running Processes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_procs_running{job=\"nodeexp\", instance=\"nodeexp:9100\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"nodeexp\", instance=\"nodeexp:9100\"} - node_memory_MemFree_bytes{job=\"nodeexp\", instance=\"nodeexp:9100\"} - node_memory_Cached_bytes{job=\"nodeexp\", instance=\"nodeexp:9100\"} - node_memory_Buffers_bytes{job=\"nodeexp\", instance=\"nodeexp:9100\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"nodeexp\", instance=\"nodeexp:9100\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"nodeexp\", instance=\"nodeexp:9100\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"nodeexp\", instance=\"nodeexp:9100\"}",
     "legendFormat": "Buffers"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"nodeexp\", instance=\"nodeexp:9100\"} - node_memory_MemFree_bytes{job=\"nodeexp\", instance=\"nodeexp:9100\"} - node_memory_Cached_bytes{job=\"nodeexp\", instance=\"nodeexp:9100\"} - node_memory_Buffers_bytes{job=\"nodeexp\", instance=\"nodeexp:9100\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"nodeexp\", instance=\"nodeexp:9100\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"nodeexp\", instance=\"nodeexp:9100\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"nodeexp\", instance=\"nodeexp:9100\"}",
     "legendFormat": "Buffers"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg without(cpu) (irate(node_cpu_seconds_total{job=\"nodeexp\", instance=\"nodeexp:9100\", mode!=\"idle\"}[1m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without(cpu) (irate(node_cpu_seconds_total{job=\"nodeexp\", instance=\"nodeexp:9100\", mode!=\"idle\"}[1m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"nodeexp\", instance=\"nodeexp:9100\", device=\"/dev/root\", fstype=\"ext4\", mountpoint=\"/\"} - node_filesystem_avail_bytes{job=\"nodeexp\", instance=\"nodeexp:9100\", device=\"/dev/root\", fstype=\"ext4\", mountpoint=\"/\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_filesystem_avail_bytes{job=\"nodeexp\", instance=\"nodeexp:9100\", device=\"/dev/root\", fstype=\"ext4\", mountpoint=\"/\"}",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{job=\"nodeexp\", instance=\"nodeexp:9100\", device=\"/dev/root\", fstype=\"ext4\", mountpoint=\"/\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "node_filesystem_size_bytes{job=\"nodeexp\", instance=\"nodeexp:9100\", device=\"/dev/root\", fstype=\"ext4\", mountpoint=\"/\"} - node_filesystem_avail_bytes{job=\"nodeexp\", instance=\"nodeexp:9100\", device=\"/dev/root\", fstype=\"ext4\", mountpoint=\"/\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"nodeexp\", instance=\"nodeexp:9100\", device=\"eth0\"}[1m])",
     "legendFormat": "Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"nodeexp\", instance=\"nodeexp:9100\", device=\"eth0\"}[1m])",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "CPU  Temp",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{job=\"nodeexp\", instance=\"nodeexp:9100\", chip=\"thermal_thermal_zone0\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  }
 ]
}