#Raspberry Pi | Home Media Server

version: "3.9"

services:
  portainer-ce:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: always
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/${USER}/tools/portainer:/data

  samba:
    container_name: samba
    image: dperson/samba:rpi
    restart: always
    command: '-u "${USER};password" -s "data;/data;yes;no"'
    stdin_open: true
    tty: true
    environment:
      - TZ=${TZ}
    ports:
      - 139:130
      - 445:445
    volumes:
      - /data:/data
