version: "3.9"

services:
  duckdns:
    container_name: duckdns
    image: ghcr.io/linuxserver/duckdns
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SUBDOMAINS=${SUBDOMAINS}
      - TOKEN=${DUCKDNS_TOKEN}
      - LOG_FILE=false
    volumes:
      - /home/${USER}/web/duckdns/config:/config

  app:
    container_name: nginx-proxy-manager
    image: "jc21/nginx-proxy-manager:latest"
    restart: always
    ports:
      - 80:80
      - 81:81
      - 443:443
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: ${DB_MYSQL_USER}
      DB_MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      DB_MYSQL_NAME: "npm"
    volumes:
      - /home/${USER}/web/nginx/data:/data
      - /home/${USER}/web/nginx/letsencrypt:/etc/letsencrypt
  db:
    container_name: maria-db
    image: "yobasystems/alpine-mariadb:latest"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_DATABASE: "npm"
      MYSQL_USER: ${DB_MYSQL_USER}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
    volumes:
      - /home/${USER}/web/nginx/data/mysql:/var/lib/mysql
